# 워크플로우 이름
name: Github Actions 실행시켜보기

# Event : 실행되는 시점 트리거
# main브랜치에 push될떄 실행됨
on:
  push:
    branches:
    - main

# 1개의 workflow에는 여러개이상의 job이 존재 가능
# 여러 job들은 병렬적으로 수행됨
jobs:
# job 이름이 My-Deploy-Job가 됨
  My-Deploy-Job:
    runs-on: ubuntu-latest
    # job은 여러 step으로 구성됨
    steps:
      - name: Hello World 찍기
      # 기본적으로 리눅스 명령어 실행
        run: echo "Hellow World"

      - name: 여러 명령어 문장 작성
        run: |
          echo "Good"
          echo "Morningzz"

      - name: Github Actions 자체에 저장되어있는 변수 사용
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY